# Generated by Django 5.2.7 on 2025-10-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='selected_options',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='feedback',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_choice_indices',
            field=models.JSONField(blank=True, help_text='List of selected choice indices: [0, 2] for first and third choices', null=True),
        ),
    ]
