# Generated by Django 5.2.7 on 2025-10-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentanswer_selected_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='score',
        ),
    ]
