# Generated by Django 5.2.7 on 2025-10-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_grading_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='selected_choice_indices',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='uploaded_image',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='answer_data',
            field=models.JSONField(default=dict, help_text='Answer data structure varies by quiz type'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='student_uploads/'),
        ),
    ]
