# Generated by Django 5.2.7 on 2025-10-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_studentanswer_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(fields=('submission',), name='unique_answer_per_submission'),
        ),
    ]
