# Generated by Django 5.2.7 on 2025-10-15 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('has_type_options', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_with_slide', models.BooleanField(default=True)),
                ('minimize_results_window_on_start', models.BooleanField(default=False)),
                ('auto_close_after_seconds', models.PositiveIntegerField(blank=True, help_text='If set, closes submissions after N seconds from start.', null=True)),
                ('show_timer', models.BooleanField(default=True)),
                ('allow_late_submissions', models.BooleanField(default=False)),
                ('show_results_to_students', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
                ('quiz_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='quizzes.quiztype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_choices', models.PositiveIntegerField(default=4)),
                ('allow_multiple_choices', models.BooleanField(default=False)),
                ('has_correct_answer', models.BooleanField(default=True)),
                ('competition_mode', models.BooleanField(default=False)),
                ('randomize_choice_order', models.BooleanField(default=True)),
                ('points_per_correct', models.PositiveIntegerField(default=1)),
                ('penalty_per_wrong', models.IntegerField(default=0)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_options', to='quizzes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUploadOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_file_size_mb', models.PositiveIntegerField(default=5)),
                ('allowed_formats', models.CharField(default='jpg,png,jpeg', max_length=100)),
                ('allow_multiple_files', models.BooleanField(default=False)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imageupload_options', to='quizzes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='DrawingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_width', models.PositiveIntegerField(default=800)),
                ('canvas_height', models.PositiveIntegerField(default=600)),
                ('allow_colors', models.BooleanField(default=True)),
                ('allow_eraser', models.BooleanField(default=True)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_options', to='quizzes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='ShortAnswerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_length', models.PositiveIntegerField(default=200)),
                ('expected_keywords', models.TextField(blank=True, help_text='Comma-separated keywords for rubric')),
                ('case_sensitive', models.BooleanField(default=False)),
                ('use_regex', models.BooleanField(default=False)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shortanswer_options', to='quizzes.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='WordCloudOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_words_per_student', models.PositiveIntegerField(default=3)),
                ('allow_duplicates', models.BooleanField(default=False)),
                ('normalize_case', models.BooleanField(default=True)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wordcloud_options', to='quizzes.quiz')),
            ],
        ),
    ]
