# Generated by Django 5.2.7 on 2025-10-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingoptions',
            name='question_text',
            field=models.TextField(default='', help_text='The prompt or instruction for the drawing'),
        ),
        migrations.AddField(
            model_name='imageuploadoptions',
            name='question_text',
            field=models.TextField(default='', help_text='The prompt or instruction for the image upload'),
        ),
        migrations.AddField(
            model_name='multiplechoiceoptions',
            name='choices',
            field=models.JSONField(default=list, help_text="List of choices with format: [{'text': 'Option A', 'is_correct': True}, ...]"),
        ),
        migrations.AddField(
            model_name='multiplechoiceoptions',
            name='question_text',
            field=models.TextField(default='', help_text='The actual question being asked'),
        ),
        migrations.AddField(
            model_name='shortansweroptions',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='The exact correct answer (optional)', null=True),
        ),
        migrations.AddField(
            model_name='shortansweroptions',
            name='question_text',
            field=models.TextField(default='', help_text='The actual question being asked'),
        ),
        migrations.AddField(
            model_name='wordcloudoptions',
            name='question_text',
            field=models.TextField(default='', help_text='The prompt or question for the word cloud'),
        ),
    ]
