# Generated by Django 5.2.7 on 2025-10-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_seed_quiz_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadoptions',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='multiplechoiceoptions',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('word_cloud', 'Word Cloud')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='shortansweroptions',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='wordcloudoptions',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='properties',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='DrawingOptions',
        ),
        migrations.DeleteModel(
            name='ImageUploadOptions',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceOptions',
        ),
        migrations.DeleteModel(
            name='QuizType',
        ),
        migrations.DeleteModel(
            name='ShortAnswerOptions',
        ),
        migrations.DeleteModel(
            name='WordCloudOptions',
        ),
    ]
