# Generated by Django 5.2.7 on 2025-10-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_remove_imageuploadoptions_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('word_cloud', 'Word Cloud'), ('drawing', 'Drawing'), ('image_upload', 'Image Upload')], max_length=50),
        ),
    ]
