# Generated by Django 5.2.7 on 2025-10-24 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('quizzes', '0004_remove_imageuploadoptions_quiz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='multi_question_id',
            field=models.UUIDField(blank=True, help_text="If set, this quiz is part of a multi-quiz. If NULL, it's a standalone quiz.", null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of this question within the multi-quiz (0 for standalone quizzes)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('word_cloud', 'Word Cloud'), ('drawing', 'Drawing'), ('image_upload', 'Image Upload')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(condition=models.Q(('multi_question_id__isnull', False)), fields=('multi_question_id', 'question_order'), name='unique_question_order_per_multi_quiz'),
        ),
    ]
