# Generated by Django 5.2.7 on 2025-10-20 20:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_code', models.CharField(editable=False, max_length=6, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('question', models.TextField(blank=True, help_text='Optional prompt for students', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('allow_anonymous', models.BooleanField(default=True)),
                ('max_submissions', models.PositiveIntegerField(default=100, help_text='Maximum number of submissions allowed')),
                ('submission_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='image_uploads/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='image_thumbnails/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_liked', models.BooleanField(default=False, help_text='Teacher liked this submission')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Image metadata (dimensions, EXIF, etc.)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='image_upload.imageuploadsession')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_download', models.BooleanField(default=False)),
                ('max_file_size_mb', models.PositiveIntegerField(default=10)),
                ('allowed_formats', models.JSONField(default=list, help_text='List of allowed file formats')),
                ('default_anonymous', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_upload_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
