# Generated by Django 5.2.7 on 2025-10-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='name',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject',
        ),
    ]
