# Generated by Django 5.2.7 on 2025-10-17 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_class_name_remove_class_subject'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('teacher', 'course'), name='unique_active_class_per_teacher_course'),
        ),
    ]
